import type { DaySnapshot } from './types'

/**
 * Stand-in for the repository layer (fixedEventRepository, flexibleTaskRepository,
 * proposalRepository). Shapes match lib/types.ts one-for-one, so swapping this
 * for real queries is a single import change in app/today/page.tsx.
 */
export const mockDay: DaySnapshot = {
  date: '2026-08-25',
  dayLabel: 'Tuesday, August 25',
  windowStart: 6 * 60,
  windowEnd: 23 * 60,

  events: [
    {
      id: 'ev_standup',
      kind: 'event',
      title: 'Engineering standup',
      startAt: 9 * 60,
      endAt: 9 * 60 + 30,
      location: 'Meet',
      priority: 'MEDIUM',
      source: 'MANUAL',
    },
    {
      id: 'ev_design_review',
      kind: 'event',
      title: 'Design review — scheduling engine',
      description: 'Walk through the proposal diff interaction.',
      startAt: 11 * 60,
      endAt: 12 * 60,
      location: 'Studio B',
      priority: 'HIGH',
      source: 'IMAGE',
    },
    {
      id: 'ev_lunch',
      kind: 'event',
      title: 'Lunch with Priya',
      startAt: 13 * 60,
      endAt: 13 * 60 + 45,
      location: 'Kaffa',
      priority: 'LOW',
      source: 'TEXT',
    },
    {
      id: 'ev_client',
      kind: 'event',
      title: 'Northwind quarterly call',
      startAt: 15 * 60 + 30,
      endAt: 16 * 60 + 30,
      location: 'Zoom',
      priority: 'CRITICAL',
      source: 'IMPORT',
    },
    {
      id: 'ev_badminton',
      kind: 'event',
      title: 'Badminton',
      startAt: 19 * 60,
      endAt: 20 * 60,
      location: 'Court 3',
      priority: 'MEDIUM',
      source: 'MANUAL',
    },
  ],

  tasks: [
    {
      id: 'tk_strength',
      kind: 'task',
      title: 'Strength session',
      estimatedMinutes: 45,
      priority: 'MEDIUM',
      status: 'COMPLETED',
      scheduledStartAt: 6 * 60 + 30,
      scheduledEndAt: 7 * 60 + 15,
    },
    {
      id: 'tk_pr_backlog',
      kind: 'task',
      title: 'Clear PR review backlog',
      estimatedMinutes: 60,
      priority: 'HIGH',
      status: 'TODO',
      scheduledStartAt: 7 * 60 + 45,
      scheduledEndAt: 8 * 60 + 45,
    },
    {
      id: 'tk_planning_brief',
      kind: 'task',
      title: 'Write Q3 planning brief',
      description: 'Needs the headcount numbers from Ravi first.',
      estimatedMinutes: 60,
      priority: 'CRITICAL',
      status: 'TODO',
      deadline: { dueAt: 18 * 60, dueDayOffset: 0, strict: true },
      scheduledStartAt: 9 * 60 + 45,
      scheduledEndAt: 10 * 60 + 45,
      scheduleReason: 'DEADLINE_RISK',
    },
    {
      id: 'tk_northwind_thread',
      kind: 'task',
      title: 'Reply to Northwind thread',
      estimatedMinutes: 30,
      priority: 'HIGH',
      status: 'TODO',
      deadline: { dueAt: 15 * 60 + 30, dueDayOffset: 0, strict: true },
      scheduledStartAt: 12 * 60 + 15,
      scheduledEndAt: 12 * 60 + 45,
      scheduleReason: 'BEFORE_DEPENDENT_EVENT',
    },
    {
      id: 'tk_window_calc',
      kind: 'task',
      title: 'Refactor the window calculator',
      description: 'Split gap-finding out of the scoring pass.',
      estimatedMinutes: 75,
      priority: 'MEDIUM',
      status: 'IN_PROGRESS',
      scheduledStartAt: 14 * 60,
      scheduledEndAt: 15 * 60 + 15,
    },
    {
      id: 'tk_retro_notes',
      kind: 'task',
      title: 'Draft sprint retro notes',
      estimatedMinutes: 45,
      priority: 'LOW',
      status: 'TODO',
      scheduledStartAt: 16 * 60 + 45,
      scheduledEndAt: 17 * 60 + 30,
      scheduleReason: 'MOVED_FROM_MORNING',
    },
    {
      id: 'tk_reading',
      kind: 'task',
      title: 'Read — Deep Work, ch. 4',
      estimatedMinutes: 45,
      priority: 'LOW',
      status: 'TODO',
      scheduledStartAt: 20 * 60 + 30,
      scheduledEndAt: 21 * 60 + 15,
    },

    // Backlog — the engine could not place these inside today's availability.
    {
      id: 'tk_renew_domain',
      kind: 'task',
      title: 'Renew dayflow.app domain',
      estimatedMinutes: 10,
      priority: 'CRITICAL',
      status: 'TODO',
      deadline: { dueAt: 23 * 60, dueDayOffset: 0, strict: true },
      scheduledStartAt: null,
      scheduledEndAt: null,
    },
    {
      id: 'tk_batched_writes',
      kind: 'task',
      title: 'Migrate proposal engine to batched writes',
      estimatedMinutes: 120,
      priority: 'HIGH',
      status: 'TODO',
      deadline: { dueAt: 12 * 60, dueDayOffset: 1, strict: true },
      scheduledStartAt: null,
      scheduledEndAt: null,
    },
    {
      id: 'tk_habit_ui',
      kind: 'task',
      title: 'Sketch habit streak UI',
      estimatedMinutes: 45,
      priority: 'MEDIUM',
      status: 'TODO',
      deadline: { dueAt: 17 * 60, dueDayOffset: 2, strict: false },
      scheduledStartAt: null,
      scheduledEndAt: null,
    },
    {
      id: 'tk_flights',
      kind: 'task',
      title: 'Book flights for the offsite',
      estimatedMinutes: 20,
      priority: 'MEDIUM',
      status: 'TODO',
      deadline: { dueAt: 10 * 60, dueDayOffset: 3, strict: false },
      scheduledStartAt: null,
      scheduledEndAt: null,
    },
    {
      id: 'tk_onboarding_docs',
      kind: 'task',
      title: 'Update onboarding docs',
      estimatedMinutes: 90,
      priority: 'LOW',
      status: 'TODO',
      scheduledStartAt: null,
      scheduledEndAt: null,
    },
  ],

  unavailable: [
    {
      id: 'av_winddown',
      type: 'UNAVAILABLE',
      startAt: 21 * 60 + 30,
      endAt: null,
      openEnded: true,
      reason: 'Wind down',
    },
  ],

  pendingProposal: {
    id: 'pr_2026_08_25',
    status: 'PENDING_REVIEW',
    changeCount: 3,
    source: 'AVAILABILITY_CHANGED',
  },
}
